version: '3'

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/10/main:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test1
      - POSTGRES_USER=projectuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=test1
      - DJANGO_DB_USERNAME=projectuser
      - DJANGO_DB_PASSWORD=password
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command:
      - python3 manage.py runserver 0:8000
    volumes:
      - ./:/phopo/

docker run -it --rm \
    -p 8000:8000 \
    --link db \
    -e DJANGO_DB_HOST=db \
    -e DJANGO_DEBUG=True \
    project \
    ./manage.py makemigrations ./manage.py migrate ./manage.py runserver 0:8000

    docker run --rm \
    --name db \
    -e POSTGRES_DB=test1 \
    -e POSTGRES_USER=projectuser \
    -e POSTGRES_PASSWORD=password \
    postgres
